# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_Anton1_rcpp_hello_world`)
}

meanC <- function(x) {
    .Call(`_Anton1_meanC`, x)
}

sumCpp <- function(x) {
    .Call(`_Anton1_sumCpp`, x)
}

to_celsius <- function(x) {
    .Call(`_Anton1_to_celsius`, x)
}

paste2 <- function(lhs, rhs) {
    .Call(`_Anton1_paste2`, lhs, rhs)
}

removePunct <- function(ori) {
    .Call(`_Anton1_removePunct`, ori)
}

removePunct2 <- function(ori) {
    .Call(`_Anton1_removePunct2`, ori)
}

